services:
  agent_websocket_local:
    container_name: agent_websocket_local
    depends_on:
    - mysql_tars_local
    - redis_offline_map
    environment:
    - ENV_CONFIG=prod
    - TZ=Asia/Shanghai
    - LOCAL_DIFY_URL=http://192.168.1.100:8089/frameWorkPortal/agent
    - LOCAL_LLM_URL=http://10.1.0.247:22
    - LOCAL_LLM_UID=LLM
    - API_KEY=xxx
    - LOCAL_EMB_URL=http://10.1.0.247:16001/v1/embeddings
    - LOCAL_EMB_UID=embedding
    - REDIS_HOST=redis_offline_map
    - REDIS_PORT=6379
    - MYSQL_HOST=10.1.0.247
    - MYSQL_PORT=3306
    - DB_DB=ee
    - DB_USER=root
    - DB_PASSWORD=tars123456
    - DB_TYPE=mysql
    - MILVUS_URL=http://milvus-standalone:19530
    - OFFLINE_PLANER_URL=http://planer-release:5000/text
    - FILE_UPLOAD_URL=http://192.168.1.100:8089/agent_proxy
    - ADMIN_URL=http://192.168.1.100:8089/agent_proxy
    - MINIO_INTERNAL_URL=http://192.168.1.100:8089/szzn-minio
    - MINIO_EXTERNAL_URL=http://192.168.1.100:8089/szzn-minio
    image: agent_local_deep:0423
    ports:
    - 16580:17850
    privileged: true
    restart: always
  milvus-standalone:
    command: milvus run standalone  1> /dev/null
    container_name: milvus-standalone
    environment:
    - ETCD_USE_EMBED=true
    - ETCD_DATA_DIR=/var/lib/milvus/etcd
    - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
    - COMMON_STORAGETYPE=local
    image: milvusdb/milvus:v2.5.8-paas
    privileged: true
    restart: always
  mysql_tars_local:
    container_name: mysql_tars_local
    environment:
    - MYSQL_ROOT_PASSWORD=tars123456
    image: mysql:deep_260328
    restart: always
  planer-release:
    container_name: planner_release
    environment:
    - REDIS_HOST=redis_offline_map
    - REDIS_PORT=6379
    image: z-planner:local_0412
    restart: always
  redis_offline_map:
    command: redis-server /etc/redis/redis.conf
    container_name: redis_offline_map
    environment: []
    image: redis:offline_map_test2
    restart: always
version: '3'
